language: go
sudo: false
go:
- 1.10.x
go_import_path: github.com/sourcegraph/src-cli
install:
- go get -d -t ./...
- go test -i ./...
- go get -u github.com/mitchellh/gox
- mkdir release
- cd release && gox -arch 'amd64' -os 'linux windows darwin' ../cmd/...
script:
- cd $TRAVIS_BUILD_DIR
- go test -race -v ./...
deploy:
  provider: releases
  api_key:
    secure: iupdYYdXAhrWMa4xKn8G9O4/Muk0DhR4qBwTkmuPjl3HZSARir/0TfEW1JpU/LgNUWg2gCVA/eMmieInADH4kroRx9d8Lfy8pwnVvFogR3Sw+OEuHtUKAf03kyGndDJWcepvVEG/qrlVBte3v7FbpDT+t30qu3GipHZ/3Rn4IOtEL/nWzlGzAC7oOUQjDseGDtt5NDXpB6Uc6hnZzCKKgWSOBrIZnOXpq/zW+SLkDKrlNTZMCPgFkAMpGoCswovyZRbNf8y0o9NKmV/TmUEekKrGHPzepCVUIOvpT5lcGwM5soFfB3KTjvcq+UBiG6BYbKPApkDjeSr3RjR20C60o8wf6cpSCTAFw/1epREMvyv4o6qKp6wAgbySYnPfg0i/PnCWMeoBt0EuM4VcrSS2a8dJRGFBdUTZLB3De/Mitd2Ves4GdhxJwr0pYxt2P+h8DxrZ84TjPZCdWd2i0Kfhq2TZl0/MB46OMpn1Eb4K7MOLO+e8uIXIDyOEvsEu1jL+UsAs10a+A0BC4Mv9tEZ86bI4MuSAX/CFVbk2tyagCMXLPMt1p80Ji9eS6zAb9OJcIrdr2qOfQ5U4+kuMitxPM3IMgJQ1NzRAZZXAojenKG8KLOa+hBZaYq9RlG4FYVFopwoRKfw0oi9aCwPQVZcRnNzM1RmDsnS/3nxy8DCepFo=
  file_glob: true
  file: release/*
  skip_cleanup: true
  on:
    tags: true
