language: go
sudo: false
go:
- 1.10.x
go_import_path: github.com/sourcegraph/src-cli
install:
- go get -d -t ./...
- go test -i ./...
- go get -u github.com/mitchellh/gox
- mkdir release
- cd release && gox -arch 'amd64' -os 'linux windows darwin' ../cmd/...
script:
- cd $TRAVIS_BUILD_DIR
- go test -race -v ./...
deploy:
  provider: releases
  api_key:
    secure: cf2om3KN/1FLDK+DPYOWhI0sNWUdL3xv2MOmbAPrDJX91z97SAT2rJDgbveaXwyxLQyueQy9EHJKoGwepfNcPV+T3cU9J8CwwnM4erh00lkTwhHOM3521rs+cEbgXcpIlr8jIPBCxCWpBapBG4tHk1Rl7zv/wfN0SwFCZFfwHzghyCNrbEoTKalCNBVR6nOv4rJR/HOUQixCWwI5OO4FQJSwwxKm9MuIS+RfJng96/I+El6WOIEISdXlVfWTlZMNX13LIOY+zD3s7F7FlB1feCDEQ3zp7NUUeiW5ncJoc1MZU2HgTBcy2YXevZrfb1zqNOJwEwoW39EcjlXYl8VhBEi/Ngy9FdBusLGtTmT8CzChF60bFLEw8z8wT5m+9IMNZ3rt1lRtz9gF5GLPM5wU0ePfxpfVxqghrGpXv4x4rNyDnazCb2w8pYFI5xWnZNWDyPcn58TXGz+t2X26ouNB67dSybW9YIoSIquSmUfhPbWASfUjhYU580lPrBp7liD03S3lNfQW3fxJyb73R9lMBnZbFqDe3px4c1I+/CWt+GqgYUFSHkqVj98RQWhYoGg49UF92SXbddGT1BsM+Kdg39fW9j9pBLNjtVbUlEnlqYN0BEb0ymm/OxIdd3S+iaIbS47AByCoDP/P0Wv8WO+j6hYYFeDmo71jPuXrkG4S/wU=
  file_glob: true
  file: release/*
  skip_cleanup: true
  on:
    tags: true
